import 'dart:convert';
import 'package:hive/hive.dart';

// Part file generated by Hive for the AdBanner class
part 'ad_banner.g.dart';

// Function to deserialize a JSON string into a list of AdBanner objects
List<AdBanner> adBannerListFromJson(String val) => List<AdBanner>.from(
    json.decode(val)['data'].map((banner) => AdBanner.fromJson(banner)));

// Hive Type Adapter for the AdBanner class
@HiveType(typeId: 1)
class AdBanner {
  // Hive Field for the 'id' attribute
  @HiveField(0)
  final int id;

  // Hive Field for the 'image' attribute
  @HiveField(1)
  final String image;

  // AdBanner class constructor
  AdBanner({
    required this.id,
    required this.image,
  });

  // Factory method to create an AdBanner instance from a JSON map
  factory AdBanner.fromJson(Map<String, dynamic> data) => AdBanner(
        id: data['id'],
        // Access nested attributes to get the image URL
        image: data['attributes']['image']['data']['attributes']['url'],
      );
}
