import 'dart:convert';
import 'package:hive/hive.dart';

// Part file generated by Hive for the Category class
part 'category.g.dart';

// Function to deserialize a JSON string into a list of popular categories
List<Category> popularCategoryListFromJson(String val) =>
    List<Category>.from(json
        .decode(val)['data']
        .map((category) => Category.popularCategoryFromJson(category)));

// Function to deserialize a JSON string into a list of categories
List<Category> categoryListFromJson(String val) => List<Category>.from(json
    .decode(val)['data']
    .map((category) => Category.categoryFromJson(category)));

// Hive Type Adapter for the Category class
@HiveType(typeId: 2)
class Category {
  // Hive Field for the 'id' attribute
  @HiveField(0)
  final int id;

  // Hive Field for the 'name' attribute
  @HiveField(1)
  final String name;

  // Hive Field for the 'image' attribute
  @HiveField(2)
  final String image;

  // Category class constructor
  Category({required this.id, required this.name, required this.image});

  // Factory method to create a popular category instance from a JSON map
  factory Category.popularCategoryFromJson(Map<String, dynamic> data) =>
      Category(
        id: data['id'],
        // Access nested attributes to get the name and image URL
        name: data['attributes']['category']['data']['attributes']['name'],
        image: data['attributes']['category']['data']['attributes']['image']
            ['data']['attributes']['url'],
      );

  // Factory method to create a category instance from a JSON map
  factory Category.categoryFromJson(Map<String, dynamic> data) => Category(
        id: data['id'],
        name: data['attributes']['name'],
        // Access nested attributes to get the image URL
        image: data['attributes']['image']['data']['attributes']['url'],
      );
}
