import 'dart:convert';
import 'package:hive/hive.dart';

// Import the Tag class for product tagging
import 'tag.dart';

// Part file generated by Hive for the Product class
part 'product.g.dart';

// Function to deserialize a JSON string into a list of popular products
List<Product> popularProductListFromJson(String val) => List<Product>.from(
    json.decode(val)['data'].map((val) => Product.popularProductFromJson(val)));

// Function to deserialize a JSON string into a list of products
List<Product> productListFromJson(String val) => List<Product>.from(
    json.decode(val)['data'].map((val) => Product.productFromJson(val)));

// Hive Type Adapter for the Product class
@HiveType(typeId: 3)
class Product {
  // Hive Field for the 'id' attribute
  @HiveField(0)
  final int id;

  // Hive Field for the 'name' attribute
  @HiveField(1)
  final String name;

  // Hive Field for the 'description' attribute
  @HiveField(2)
  final String description;

  // Hive Field for the 'images' attribute
  @HiveField(3)
  final List<String> images;

  // Hive Field for the 'tags' attribute
  @HiveField(4)
  final List<Tag> tags;

  // Product class constructor
  Product({
    required this.id,
    required this.name,
    required this.description,
    required this.images,
    required this.tags,
  });

  // Factory method to create a popular product instance from a JSON map
  factory Product.popularProductFromJson(Map<String, dynamic> data) => Product(
        id: data['id'],
        // Access nested attributes to get the name, description, and images
        name: data['attributes']['product']['data']['attributes']['name'],
        description: data['attributes']['product']['data']['attributes']
            ['description'],
        images: List<String>.from(data['attributes']['product']['data']
                ['attributes']['images']['data']
            .map((image) => image['attributes']['url'])),
        tags: [],
      );

  // Factory method to create a product instance from a JSON map
  factory Product.productFromJson(Map<String, dynamic> data) => Product(
        id: data['id'],
        name: data['attributes']['name'],
        description: data['attributes']['description'],
        images: List<String>.from(data['attributes']['images']['data']
            .map((image) => image['attributes']['url'])),
        tags: List<Tag>.from(
            data['attributes']['tags']['data'].map((val) => Tag.fromJson(val))),
      );
}
